title: Karthik Garimella
show_writing: false

# Posts + Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Put posts under /writing/YYYY/MM/DD/title/
permalink: /writing/:year/:month/:day/:title/

# Default layout for posts so you don't have to write 'layout: post' each time
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
